# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: sophiahuynh.com
title: Sophia Huynh
email: sph.huynh@gmail.com
author: Sophia Huynh
description: > # "Just a place to document my work
copyright: 'Copyright &copy; 2015 Sophia Huynh. All Rights Reserved.'
credits: 'Credits: Landing Page <a href="http://ironsummitmedia.github.io/startbootstrap-landing-page"> Bootstrap</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/sphaech
  - title: github
    url: https://github.com/sph-huynh
  - title: linkedin
    url: au.linkedin.com/in/sphhuynh
