# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: soph.es
title: Sophia Huynh
email: gday@soph.es
author: Sophia Huynh
description: > # "Just a place to document my work
copyright: 'Copyright &copy; 2015 Sophia Huynh. All Rights Reserved.'

